import {
  AIKnowledgeChunk,
  Announcement,
  Book,
  Chapter,
  Question,
  Student,
  Subject,
  Topic,
} from "@/types";
import {
  MATERIAL_SUBJECTS,
  MATERIAL_BOOKS,
  MATERIAL_CHAPTERS,
} from "@/lib/learning-materials";
import {
  ALL_PRACTICE_QUESTIONS,
  QUESTION_COUNTS_BY_CHAPTER,
} from "@/lib/data/questions";

export const INITIAL_SUBJECTS: Subject[] = [
  ...MATERIAL_SUBJECTS,
  {
    id: "sub-cs",
    streamId: "Computer Science",
    name: "Computer Science",
    code: "CS-12",
    icon: "code",
    description:
      "Tamil Nadu State Board Class 12 Computer Science (Python, OOP, Database & SQL)",
    orderIndex: 1,
    totalChapters: 16,
  },
  {
    id: "sub-botany",
    streamId: "Biology",
    name: "Bio-Botany",
    code: "BOT-12",
    icon: "leaf",
    description:
      "Class 12 Bio-Botany: Plant Reproduction, Classical Genetics, Biotechnology & Ecology",
    orderIndex: 2,
    totalChapters: 10,
  },
  {
    id: "sub-zoology",
    streamId: "Biology",
    name: "Bio-Zoology",
    code: "ZOO-12",
    icon: "dna",
    description:
      "Class 12 Bio-Zoology: Human Reproduction, Genetics, Health, Evolution & Conservation",
    orderIndex: 3,
    totalChapters: 12,
  },
];

export const INITIAL_BOOKS: Book[] = [
  ...MATERIAL_BOOKS,
  {
    id: "book-cs",
    subjectId: "sub-cs",
    name: "Computer Science - Standard 12",
    volume: "Volume I & II Combined",
    description: "Official TN SCERT Textbook for Class 12 Computer Science",
    orderIndex: 1,
  },
  {
    id: "book-botany",
    subjectId: "sub-botany",
    name: "Bio-Botany - Standard 12",
    volume: "Volume I",
    description: "Official TN SCERT Textbook for Class 12 Bio-Botany",
    orderIndex: 1,
  },
  {
    id: "book-zoology",
    subjectId: "sub-zoology",
    name: "Bio-Zoology - Standard 12",
    volume: "Volume I",
    description: "Official TN SCERT Textbook for Class 12 Bio-Zoology",
    orderIndex: 1,
  },
];

const RAW_CHAPTERS: Chapter[] = [
  ...MATERIAL_CHAPTERS,
  // --- COMPUTER SCIENCE (16 Chapters) ---
  {
    id: "cs-ch-1",
    subjectId: "sub-cs",
    bookId: "book-cs",
    chapterNumber: 1,
    title: "Function",
    titleTamil: "செயற்கூறு",
    description:
      "Functions, function specification, parameters vs arguments, pure and impure functions",
    totalNotes: 2,
    totalVideos: 2,
    totalMcqs: 15,
    isActive: true,
    orderIndex: 1,
  },
  {
    id: "cs-ch-2",
    subjectId: "sub-cs",
    bookId: "book-cs",
    chapterNumber: 2,
    title: "Data Abstraction",
    titleTamil: "தரவு அருவமாக்கம்",
    description:
      "Abstract Data Types, Constructors and Selectors, representation of abstract data types using Pair and List",
    totalNotes: 1,
    totalVideos: 1,
    totalMcqs: 12,
    isActive: true,
    orderIndex: 2,
  },
  {
    id: "cs-ch-3",
    subjectId: "sub-cs",
    bookId: "book-cs",
    chapterNumber: 3,
    title: "Scoping",
    titleTamil: "வரையெல்லை",
    description:
      "Scope, LEGB rule, Local, Enclosing, Global, and Built-in scopes, Module variable scope",
    totalNotes: 2,
    totalVideos: 1,
    totalMcqs: 14,
    isActive: true,
    orderIndex: 3,
  },
  {
    id: "cs-ch-4",
    subjectId: "sub-cs",
    bookId: "book-cs",
    chapterNumber: 4,
    title: "Algorithmic Strategies",
    titleTamil: "நெறிமுறையின் உத்திகள்",
    description:
      "Algorithm characteristics, Time and Space complexity, Asymptotic notations (Big O, Omega, Theta), Searching & Sorting",
    totalNotes: 2,
    totalVideos: 2,
    totalMcqs: 16,
    isActive: true,
    orderIndex: 4,
  },
  {
    id: "cs-ch-5",
    subjectId: "sub-cs",
    bookId: "book-cs",
    chapterNumber: 5,
    title: "Python - Variables and Operators",
    titleTamil: "பைத்தான் - மாறிகள் மற்றும் செயற்குறிகள்",
    description:
      "Introduction to Python, tokens, keywords, identifiers, operators, input and output functions",
    totalNotes: 2,
    totalVideos: 2,
    totalMcqs: 18,
    isActive: true,
    orderIndex: 5,
  },
  {
    id: "cs-ch-6",
    subjectId: "sub-cs",
    bookId: "book-cs",
    chapterNumber: 6,
    title: "Control Structures",
    titleTamil: "கட்டுப்பாட்டு அமைப்புகள்",
    description:
      "Sequential, Alternative/Branching (if-else, elif), Iterative/Looping (while, for), jump statements (break, continue, pass)",
    totalNotes: 2,
    totalVideos: 2,
    totalMcqs: 20,
    isActive: true,
    orderIndex: 6,
  },
  {
    id: "cs-ch-7",
    subjectId: "sub-cs",
    bookId: "book-cs",
    chapterNumber: 7,
    title: "Python Functions",
    titleTamil: "பைத்தான் செயற்கூறுகள்",
    description:
      "Defining functions, arguments (positional, keyword, default, variable-length), lambda functions, recursion",
    totalNotes: 2,
    totalVideos: 2,
    totalMcqs: 20,
    isActive: true,
    orderIndex: 7,
  },
  {
    id: "cs-ch-8",
    subjectId: "sub-cs",
    bookId: "book-cs",
    chapterNumber: 8,
    title: "Strings and String Manipulation",
    titleTamil: "சரங்கள் மற்றும் சரங்களை கையாளுதல்",
    description:
      "Creating strings, indexing, slicing, immutability, escape sequences, formatting operators, built-in string functions",
    totalNotes: 1,
    totalVideos: 1,
    totalMcqs: 15,
    isActive: true,
    orderIndex: 8,
  },
  {
    id: "cs-ch-9",
    subjectId: "sub-cs",
    bookId: "book-cs",
    chapterNumber: 9,
    title: "Lists, Tuples, Sets and Dictionary",
    titleTamil: "பட்டியல், டியூப்பிள், தொகுப்பு மற்றும் அகராதி",
    description:
      "Sequential data types: List vs Tuple vs Set vs Dictionary, comprehensions, methods and operations",
    totalNotes: 2,
    totalVideos: 2,
    totalMcqs: 20,
    isActive: true,
    orderIndex: 9,
  },
  {
    id: "cs-ch-10",
    subjectId: "sub-cs",
    bookId: "book-cs",
    chapterNumber: 10,
    title: "Python Classes and Objects",
    titleTamil: "பைத்தான் இனக்குழுக்கள் மற்றும் பொருள்கள்",
    description:
      "OOP concepts, class definition, creating objects, class members, constructors (__init__), destructor, private vs public",
    totalNotes: 2,
    totalVideos: 1,
    totalMcqs: 16,
    isActive: true,
    orderIndex: 10,
  },
  {
    id: "cs-ch-11",
    subjectId: "sub-cs",
    bookId: "book-cs",
    chapterNumber: 11,
    title: "Database Concepts",
    titleTamil: "தரவுத்தள கருத்துருக்கள்",
    description:
      "DBMS concepts, data models, relational data model, components of DBMS, types of keys (primary, candidate, foreign)",
    totalNotes: 1,
    totalVideos: 1,
    totalMcqs: 14,
    isActive: true,
    orderIndex: 11,
  },
  {
    id: "cs-ch-12",
    subjectId: "sub-cs",
    bookId: "book-cs",
    chapterNumber: 12,
    title: "Structured Query Language (SQL)",
    titleTamil: "அமைப்பமை வினவல் மொழி (SQL)",
    description:
      "SQL components (DDL, DML, DCL, DQL, TCL), SQL commands, constraints, table creation, queries",
    totalNotes: 2,
    totalVideos: 2,
    totalMcqs: 20,
    isActive: true,
    orderIndex: 12,
  },
  {
    id: "cs-ch-13",
    subjectId: "sub-cs",
    bookId: "book-cs",
    chapterNumber: 13,
    title: "Python and CSV Files",
    titleTamil: "பைத்தான் மற்றும் சி.எஸ்.வி கோப்புகள்",
    description:
      "CSV files, reading CSV with reader() and DictReader(), writing CSV with writer() and DictWriter()",
    totalNotes: 1,
    totalVideos: 1,
    totalMcqs: 14,
    isActive: true,
    orderIndex: 13,
  },
  {
    id: "cs-ch-14",
    subjectId: "sub-cs",
    bookId: "book-cs",
    chapterNumber: 14,
    title: "Importing C++ Programs in Python",
    titleTamil: "பைத்தானில் சி++ நிரல்களை தருவித்தல்",
    description:
      "Scripting language vs programming language, MinGW, g++, wrapping C++ in Python using ctypes / os.system",
    totalNotes: 1,
    totalVideos: 1,
    totalMcqs: 12,
    isActive: true,
    orderIndex: 14,
  },
  {
    id: "cs-ch-15",
    subjectId: "sub-cs",
    bookId: "book-cs",
    chapterNumber: 15,
    title: "Data Manipulation Through SQL",
    titleTamil: "SQL மூலம் தரவு கையாளுதல்",
    description:
      "SQLite with Python (sqlite3 module), connect, cursor, execute, fetchone, fetchall, aggregates and group by",
    totalNotes: 1,
    totalVideos: 1,
    totalMcqs: 15,
    isActive: true,
    orderIndex: 15,
  },
  {
    id: "cs-ch-16",
    subjectId: "sub-cs",
    bookId: "book-cs",
    chapterNumber: 16,
    title: "Data Visualization Using Pyplot",
    titleTamil: "Pyplot பயன்படுத்தி தரவு காட்சிப்படுத்துதல்",
    description:
      "Matplotlib, pyplot, line chart, bar chart, pie chart, histogram, labels, title, legend, styling graphs",
    totalNotes: 1,
    totalVideos: 1,
    totalMcqs: 14,
    isActive: true,
    orderIndex: 16,
  },

  // --- BIO-BOTANY (10 Chapters) ---
  {
    id: "bot-ch-1",
    subjectId: "sub-botany",
    bookId: "book-botany",
    chapterNumber: 1,
    title: "Asexual and Sexual Reproduction in Plants",
    titleTamil: "தாவரங்களில் பாலிலா மற்றும் பாலினப் பெருக்கம்",
    description:
      "Vegetative propagation, microsporogenesis, megasporogenesis, pollination, fertilization, endosperm, embryogenesis",
    totalNotes: 2,
    totalVideos: 2,
    totalMcqs: 18,
    isActive: true,
    orderIndex: 1,
  },
  {
    id: "bot-ch-2",
    subjectId: "sub-botany",
    bookId: "book-botany",
    chapterNumber: 2,
    title: "Classical Genetics",
    titleTamil: "பாரம்பரிய மரபியல்",
    description:
      "Mendelian inheritance, monohybrid & dihybrid cross, incomplete dominance, codominance, lethal genes, epistasis",
    totalNotes: 2,
    totalVideos: 2,
    totalMcqs: 16,
    isActive: true,
    orderIndex: 2,
  },
  {
    id: "bot-ch-3",
    subjectId: "sub-botany",
    bookId: "book-botany",
    chapterNumber: 3,
    title: "Chromosomal Basis of Inheritance",
    titleTamil: "மரபுவழி அடிப்படை குரோமோசோம்",
    description:
      "Linkage, crossing over, gene mapping, multiple alleles, sex determination in plants, mutation, ploidy",
    totalNotes: 2,
    totalVideos: 1,
    totalMcqs: 15,
    isActive: true,
    orderIndex: 3,
  },
  {
    id: "bot-ch-4",
    subjectId: "sub-botany",
    bookId: "book-botany",
    chapterNumber: 4,
    title: "Principles and Processes of Biotechnology",
    titleTamil: "உயிர்த்தொழில்நுட்பவியல் கோட்பாடுகள் மற்றும் செயல்முறைகள்",
    description:
      "Tools of genetic engineering, restriction enzymes, cloning vectors, DNA ligase, PCR, gene transfer methods",
    totalNotes: 2,
    totalVideos: 2,
    totalMcqs: 18,
    isActive: true,
    orderIndex: 4,
  },
  {
    id: "bot-ch-5",
    subjectId: "sub-botany",
    bookId: "book-botany",
    chapterNumber: 5,
    title: "Plant Tissue Culture",
    titleTamil: "தாவர திசு வளர்ப்பு",
    description:
      "Totipotency, nutrient media (MS media), sterilization, callogenesis, embryogenesis, protoplast culture, cryopreservation",
    totalNotes: 1,
    totalVideos: 1,
    totalMcqs: 14,
    isActive: true,
    orderIndex: 5,
  },
  {
    id: "bot-ch-6",
    subjectId: "sub-botany",
    bookId: "book-botany",
    chapterNumber: 6,
    title: "Principles of Ecology",
    titleTamil: "சூழலியல் கோட்பாடுகள்",
    description:
      "Ecological factors (climatic, edaphic, biotic), morphological & anatomical adaptations in hydrophytes and xerophytes",
    totalNotes: 1,
    totalVideos: 1,
    totalMcqs: 15,
    isActive: true,
    orderIndex: 6,
  },
  {
    id: "bot-ch-7",
    subjectId: "sub-botany",
    bookId: "book-botany",
    chapterNumber: 7,
    title: "Ecosystem",
    titleTamil: "சூழ்நிலை மண்டலம்",
    description:
      "Structure, food chain, food web, ecological pyramids, energy flow, carbon and phosphorus cycling, succession",
    totalNotes: 2,
    totalVideos: 1,
    totalMcqs: 16,
    isActive: true,
    orderIndex: 7,
  },
  {
    id: "bot-ch-8",
    subjectId: "sub-botany",
    bookId: "book-botany",
    chapterNumber: 8,
    title: "Environmental Issues",
    titleTamil: "சுற்றுச்சூழல் பிரச்சனைகள்",
    description:
      "Air pollution, water pollution, global warming, ozone depletion, deforestation, afforestation, carbon sequestration",
    totalNotes: 1,
    totalVideos: 1,
    totalMcqs: 15,
    isActive: true,
    orderIndex: 8,
  },
  {
    id: "bot-ch-9",
    subjectId: "sub-botany",
    bookId: "book-botany",
    chapterNumber: 9,
    title: "Plant Breeding",
    titleTamil: "பயிர் பெருக்கம்",
    description:
      "Conventional breeding, hybridization, heterosis, mutation breeding, biofortification, disease-resistant crops",
    totalNotes: 1,
    totalVideos: 1,
    totalMcqs: 14,
    isActive: true,
    orderIndex: 9,
  },
  {
    id: "bot-ch-10",
    subjectId: "sub-botany",
    bookId: "book-botany",
    chapterNumber: 10,
    title: "Economically Useful Plants and Entrepreneurial Botany",
    titleTamil: "பொருளாதார பயனுள்ள தாவரங்கள் மற்றும் தொழில்முனைவோர் தாவரவியல்",
    description:
      "Medicinal plants, spices, biofuels, organic farming, mushroom cultivation, single cell protein",
    totalNotes: 1,
    totalVideos: 1,
    totalMcqs: 14,
    isActive: true,
    orderIndex: 10,
  },

  // --- BIO-ZOOLOGY (12 Chapters) ---
  {
    id: "zoo-ch-1",
    subjectId: "sub-zoology",
    bookId: "book-zoology",
    chapterNumber: 1,
    title: "Reproduction in Organisms",
    titleTamil: "உயிரினங்களில் இனப்பெருக்கம்",
    description:
      "Asexual reproduction (fission, budding, regeneration), sexual reproduction phases, syngamy, conjugation",
    totalNotes: 1,
    totalVideos: 1,
    totalMcqs: 15,
    isActive: true,
    orderIndex: 1,
  },
  {
    id: "zoo-ch-2",
    subjectId: "sub-zoology",
    bookId: "book-zoology",
    chapterNumber: 2,
    title: "Human Reproduction",
    titleTamil: "மனித இனப்பெருக்கம்",
    description:
      "Male & female reproductive systems, gametogenesis, menstrual cycle, fertilization, cleavage, implantation, lactation",
    totalNotes: 2,
    totalVideos: 2,
    totalMcqs: 20,
    isActive: true,
    orderIndex: 2,
  },
  {
    id: "zoo-ch-3",
    subjectId: "sub-zoology",
    bookId: "book-zoology",
    chapterNumber: 3,
    title: "Reproductive Health",
    titleTamil: "இனப்பெருக்க நலன்",
    description:
      "Need for reproductive health, contraception, amniocentesis, MTP, STIs, infertility causes & ART methods (IVF, ICSI, ZIFT)",
    totalNotes: 1,
    totalVideos: 1,
    totalMcqs: 16,
    isActive: true,
    orderIndex: 3,
  },
  {
    id: "zoo-ch-4",
    subjectId: "sub-zoology",
    bookId: "book-zoology",
    chapterNumber: 4,
    title: "Principles of Inheritance and Variation",
    titleTamil: "மரபுவழி மற்றும் மாறுபாட்டின் கோட்பாடுகள்",
    description:
      "Sex-linked inheritance (haemophilia, color blindness), sex determination in humans, karyotyping, genetic disorders",
    totalNotes: 2,
    totalVideos: 2,
    totalMcqs: 18,
    isActive: true,
    orderIndex: 4,
  },
  {
    id: "zoo-ch-5",
    subjectId: "sub-zoology",
    bookId: "book-zoology",
    chapterNumber: 5,
    title: "Molecular Genetics",
    titleTamil: "மூலக்கூறு மரபியல்",
    description:
      "DNA as genetic material, DNA replication, transcription, genetic code, translation, operon concept, Human Genome Project",
    totalNotes: 2,
    totalVideos: 2,
    totalMcqs: 20,
    isActive: true,
    orderIndex: 5,
  },
  {
    id: "zoo-ch-6",
    subjectId: "sub-zoology",
    bookId: "book-zoology",
    chapterNumber: 6,
    title: "Evolution",
    titleTamil: "பரிணாமம்",
    description:
      "Origin of life, theories of evolution (Lamarckism, Darwinism, Mutation theory), Hardy-Weinberg principle, human evolution",
    totalNotes: 2,
    totalVideos: 1,
    totalMcqs: 16,
    isActive: true,
    orderIndex: 6,
  },
  {
    id: "zoo-ch-7",
    subjectId: "sub-zoology",
    bookId: "book-zoology",
    chapterNumber: 7,
    title: "Human Health and Diseases",
    titleTamil: "மனித நலன் மற்றும் நோய்கள்",
    description:
      "Infectious & non-infectious diseases, immunity (innate & acquired), lymphoid organs, vaccines, autoimmune diseases, AIDS, cancer",
    totalNotes: 2,
    totalVideos: 2,
    totalMcqs: 20,
    isActive: true,
    orderIndex: 7,
  },
  {
    id: "zoo-ch-8",
    subjectId: "sub-zoology",
    bookId: "book-zoology",
    chapterNumber: 8,
    title: "Microbes in Human Welfare",
    titleTamil: "மனித நலனில் நுண்ணுயிரிகள்",
    description:
      "Microbes in household food processing, industrial products, sewage treatment, biogas, biocontrol agents, biofertilizers",
    totalNotes: 1,
    totalVideos: 1,
    totalMcqs: 15,
    isActive: true,
    orderIndex: 8,
  },
  {
    id: "zoo-ch-9",
    subjectId: "sub-zoology",
    bookId: "book-zoology",
    chapterNumber: 9,
    title: "Applications of Biotechnology",
    titleTamil: "உயிர்த்தொழில்நுட்பவியலின் பயன்பாடுகள்",
    description:
      "Recombinant insulin, gene therapy, transgenic animals, molecular diagnosis, stem cell therapy, biosafety & bioethics",
    totalNotes: 1,
    totalVideos: 1,
    totalMcqs: 16,
    isActive: true,
    orderIndex: 9,
  },
  {
    id: "zoo-ch-10",
    subjectId: "sub-zoology",
    bookId: "book-zoology",
    chapterNumber: 10,
    title: "Organisms and Population",
    titleTamil: "உயிரினங்கள் மற்றும் இனக்கூட்டம்",
    description:
      "Organism and its environment, major abiotic factors, population attributes, growth models, population interactions",
    totalNotes: 1,
    totalVideos: 1,
    totalMcqs: 15,
    isActive: true,
    orderIndex: 10,
  },
  {
    id: "zoo-ch-11",
    subjectId: "sub-zoology",
    bookId: "book-zoology",
    chapterNumber: 11,
    title: "Biodiversity and its Conservation",
    titleTamil: "உயிர்ப்பன்மயம் மற்றும் அதன் பாதுகாப்பு",
    description:
      "Levels of biodiversity, patterns, threats, red data book, in-situ and ex-situ conservation, biosphere reserves",
    totalNotes: 1,
    totalVideos: 1,
    totalMcqs: 16,
    isActive: true,
    orderIndex: 11,
  },
  {
    id: "zoo-ch-12",
    subjectId: "sub-zoology",
    bookId: "book-zoology",
    chapterNumber: 12,
    title: "Environmental Issues",
    titleTamil: "சுற்றுச்சூழல் பிரச்சனைகள்",
    description:
      "Pollution types, solid waste management, e-waste, radioactive wastes, greenhouse effect, ozone depletion",
    totalNotes: 1,
    totalVideos: 1,
    totalMcqs: 14,
    isActive: true,
    orderIndex: 12,
  },
];

export const INITIAL_CHAPTERS: Chapter[] = RAW_CHAPTERS.map((ch) => ({
  ...ch,
  totalMcqs: QUESTION_COUNTS_BY_CHAPTER[ch.id] ?? 0,
}));

export const INITIAL_TOPICS: Topic[] = [
  {
    id: "top-cs-1-1",
    chapterId: "cs-ch-1",
    title: "Function Specification & Definition",
    titleTamil: "செயற்கூறு வரையறை",
    orderIndex: 1,
  },
  {
    id: "top-cs-1-2",
    chapterId: "cs-ch-1",
    title: "Parameters vs Arguments",
    titleTamil: "அளபுருக்கள் vs செயலுருபுகள்",
    orderIndex: 2,
  },
  {
    id: "top-cs-1-3",
    chapterId: "cs-ch-1",
    title: "Pure and Impure Functions",
    titleTamil: "தூய மற்றும் தூய்மையற்ற செயற்கூறுகள்",
    orderIndex: 3,
  },
  {
    id: "top-cs-7-1",
    chapterId: "cs-ch-7",
    title: "Types of Function Arguments",
    titleTamil: "செயற்கூறு செயலுருபுகளின் வகைகள்",
    orderIndex: 1,
  },
  {
    id: "top-cs-7-2",
    chapterId: "cs-ch-7",
    title: "Anonymous / Lambda Functions",
    titleTamil: "பெயரிலா / லேம்ப்டா செயற்கூறுகள்",
    orderIndex: 2,
  },
  {
    id: "top-cs-12-1",
    chapterId: "cs-ch-12",
    title: "SQL Components (DDL, DML, TCL)",
    titleTamil: "SQL கூறுகள்",
    orderIndex: 1,
  },
  {
    id: "top-cs-12-2",
    chapterId: "cs-ch-12",
    title: "Constraints & Table Creation",
    titleTamil: "கட்டுப்பாடுகள் மற்றும் அட்டவணை உருவாக்கம்",
    orderIndex: 2,
  },
  {
    id: "top-bot-1-1",
    chapterId: "bot-ch-1",
    title: "Modes of Reproduction & Pollination",
    titleTamil: "இனப்பெருக்க முறைகள் மற்றும் மகரந்தச் சேர்க்கை",
    orderIndex: 1,
  },
  {
    id: "top-bot-4-1",
    chapterId: "bot-ch-4",
    title: "Recombinant DNA Technology Tools",
    titleTamil: "மீள்சேர்க்கை டிஎன்ஏ தொழில்நுட்ப கருவிகள்",
    orderIndex: 1,
  },
  {
    id: "top-zoo-2-1",
    chapterId: "zoo-ch-2",
    title: "Gametogenesis & Fertilization",
    titleTamil: "இனச்செல் உருவாக்கம் மற்றும் கருவுறுதல்",
    orderIndex: 1,
  },
  {
    id: "top-zoo-5-1",
    chapterId: "zoo-ch-5",
    title: "DNA Replication & Genetic Code",
    titleTamil: "டிஎன்ஏ இரட்டிப்பாதல் மற்றும் மரபியல் குறியீடு",
    orderIndex: 1,
  },
];

// Notes and videos are supplied by the school through the content studio.

export const INITIAL_QUESTIONS: Question[] = ALL_PRACTICE_QUESTIONS;

export const INITIAL_ANNOUNCEMENTS: Announcement[] = [
  {
    id: "ann-1",
    title: "Class 12 Mid-Term Practice Test Series Announced",
    description:
      "All Computer Science and Biology students are requested to complete the Daily 25 practice drill before October 15. The AI Study Helper has been updated with latest syllabus citations.",
    priority: "High",
    targetStream: "All",
    publishDate: "2026-10-01",
    isActive: true,
  },
  {
    id: "ann-2",
    title: "New Handwritten Notes: Python Functions & Reproduction in Plants",
    description:
      "Complete verified handwritten notes by AVS senior faculty have been uploaded with dark-mode page reader support.",
    priority: "Normal",
    targetStream: "All",
    publishDate: "2026-09-28",
    isActive: true,
  },
  {
    id: "ann-3",
    title: "Biology Model Exam 1 Timed Test is Now Active",
    description:
      "Bio-Botany and Bio-Zoology combined 50-mark model MCQ test is now open with strict server-side timer validation.",
    priority: "Urgent",
    targetStream: "Biology",
    publishDate: "2026-10-04",
    isActive: true,
  },
];

export const INITIAL_DEMO_STUDENTS: Student[] = [
  {
    id: "demo-stud-1",
    userId: "user-demo-cs",
    studentId: "AVSCS26-0001",
    studentName: "Demo CS Student",
    registerNumber: "12CS202601",
    schoolName: "Demo School (sample only)",
    studentEmail: "demo-cs@example.test",
    studentPhone: "+91 9842100001",
    stream: "Computer Science",
    medium: "English",
    academicYear: "2026-2027",
    activeStatus: true,
    mustChangePassword: false,
    createdAt: "2026-09-01T08:00:00Z",
  },
  {
    id: "demo-stud-2",
    userId: "user-demo-bio",
    studentId: "AVSBIO26-0001",
    studentName: "Demo Biology Student",
    registerNumber: "12BIO202601",
    schoolName: "Demo School (sample only)",
    studentEmail: "demo-biology@example.test",
    studentPhone: "+91 9842100002",
    stream: "Biology",
    medium: "English",
    academicYear: "2026-2027",
    activeStatus: true,
    mustChangePassword: false,
    createdAt: "2026-09-01T08:00:00Z",
  },
];

export const INITIAL_KNOWLEDGE_CHUNKS: AIKnowledgeChunk[] = [
  {
    id: "kc-cs-1",
    stream: "Computer Science",
    subjectName: "Computer Science",
    chapterTitle: "Chapter 1: Function",
    topicTitle: "Pure Functions & Function Specification",
    chunkText:
      "A Pure Function is a function that always produces the same return value for the exact same arguments and has no side effects on program state, external variables, or I/O operations. Examples include mathematical functions like square(x), sin(x), sqrt(x). An Impure function on the other hand may return different results for identical arguments or modify external/global state, such as random() or a function that updates an external accumulator. Pure functions enjoy Referential Transparency, meaning their call can be replaced with the computed result without changing program correctness.",
    chunkTextTamil:
      "தூய செயற்கூறு (Pure Function) என்பது அதே உள்ளீடுகளுக்கு எப்போதும் ஒரே விடையைத் தரும் மற்றும் வெளிப்புற மாறிகளையோ நிலைகளையோ மாற்றாத செயற்கூறு ஆகும். எ.கா: square(x), sin(x). தூய்மையற்ற செயற்கூறு பக்கவிளைவுகளை உண்டாக்கும்.",
    sourceType: "Handwritten Note",
  },
  {
    id: "kc-cs-7",
    stream: "Computer Science",
    subjectName: "Computer Science",
    chapterTitle: "Chapter 7: Python Functions",
    topicTitle: "Types of Arguments & Lambda Functions",
    chunkText:
      "Python supports four distinct argument types: 1) Positional or Required Arguments, where arguments must be passed in correct positional order; 2) Keyword Arguments, where arguments are passed with parameter names like f(name='Raj', age=17); 3) Default Arguments, which provide default fallback values if the caller omits that parameter; 4) Variable-length Arguments, denoted by *args (returns a tuple of arguments) or **kwargs (returns a dictionary of keyword arguments). Anonymous functions in Python are created using the 'lambda' keyword, taking syntax: lambda arguments: expression. Lambda functions are evaluated at runtime and return an expression value directly.",
    chunkTextTamil:
      "பைத்தானில் 4 வகை செயலுருபுகள் உள்ளன: 1) தேவையான செயலுருபுகள், 2) சிறப்புச்சொல் செயலுருபுகள், 3) கொடாநிலை செயலுருபுகள், 4) மாறும் நீள செயலுருபுகள் (*args). லேம்ப்டா (lambda) என்பது பெயரற்ற சிறிய செயற்கூறு ஆகும்.",
    sourceType: "Handwritten Note",
  },
  {
    id: "kc-bot-1",
    stream: "Biology",
    subjectName: "Bio-Botany",
    chapterTitle: "Chapter 1: Asexual and Sexual Reproduction in Plants",
    topicTitle: "Anther Wall Layers & Tapetum",
    chunkText:
      "The anther wall consists of four sequential concentric layers from outside to inside: 1) Epidermis (single protective outermost layer), 2) Endothecium (radially elongated cells with hygroscopic alpha-cellulose fibrous bands assisting dehiscence), 3) Middle layers (2 to 3 ephemeral layers that crush at maturity), and 4) Tapetum (innermost physiological layer). The Tapetum provides essential nutrients to developing microspores, secretes callase enzyme, synthesizes Ubisch bodies, and contributes sporopollenin precursors (carotenoids) to build the resistant exine layer of pollen grains.",
    chunkTextTamil:
      "மகரந்தப்பை சுவரானது வெளிப்புறத்திலிருந்து உள்ளே: 1) எபிடெர்மிஸ், 2) எண்டோதீசியம், 3) இடை அடுக்குகள், 4) டேப்பிட்டம் என்ற 4 அடுக்குகளைக் கொண்டது. டேப்பிட்டம் வளரும் நுண்வித்திகளுக்கு ஊட்டமளிக்கிறது மற்றும் ஸ்போரோபோலினின் முன்னோடிப் பொருட்களை உற்பத்தி செய்கிறது.",
    sourceType: "Syllabus Concept",
  },
  {
    id: "kc-zoo-2",
    stream: "Biology",
    subjectName: "Bio-Zoology",
    chapterTitle: "Chapter 2: Human Reproduction",
    topicTitle: "Menstrual Cycle & Hormonal Regulation",
    chunkText:
      "The human menstrual cycle spans approximately 28 days and comprises four sequential phases: 1) Menstrual phase (Days 1 to 5), triggered by sharp reduction in progesterone and estrogen causing endometrial sloughing; 2) Follicular or Proliferative phase (Days 6 to 13), driven by pituitary FSH stimulating primary follicles to mature into Graafian follicles and secrete estrogen; 3) Ovulatory phase (Day 14), triggered by the rapid LH surge causing Graafian follicle rupture and secondary oocyte release; 4) Luteal or Secretory phase (Days 15 to 28), during which the collapsed follicle transforms into the Corpus Luteum, secreting large quantities of progesterone to prepare the endometrium for blastocyst implantation.",
    chunkTextTamil:
      "மனித மாதவிடாய் சுழற்சி 4 நிலைகளைக் கொண்டுள்ளது: 1) மாதவிடாய் நிலை (1-5 நாட்கள்), 2) பாலிக்கிள் நிலை (6-13 நாட்கள் - FSH தூண்டுதல்), 3) அண்டவெளியீட்டு நிலை (14-வது நாள் - LH எழுச்சி), 4) லூட்டியல் நிலை (15-28 நாட்கள் - கார்பஸ் லூட்டியம் புரோஜெஸ்டிரோன் சுரத்தல்).",
    sourceType: "NotebookLM Summary",
  },
];
