import { mkdirSync } from "node:fs";
import type { Question } from "../src/types";

mkdirSync("src/lib/data/questions", { recursive: true });

export const CS_BOOK_ID = "12-computer-science-english-37bdae5b";

export const csQuestionsData: Omit<Question, "id" | "createdAt">[] = [
  // ================= CHAPTER 1: FUNCTION =================
  {
    chapterId: "cs-ch-1",
    subjectId: "sub-cs",
    stream: "Computer Science",
    sourceType: "Book-In",
    status: "Teacher Review",
    difficulty: "Easy",
    sourceTextbookId: CS_BOOK_ID,
    sourcePage: 14,
    sourceQuestionNumber: 1,
    sourcePresentation: "Text",
    questionText: "The small sections of code that are used to perform a particular task is called:",
    questionTextTamil: "ஒரு குறிப்பிட்ட செயலை செய்வதற்காகப் பயன்படும் குறிமுறையின் சிறிய பகுதி:",
    optionA: "Subroutines",
    optionB: "Files",
    optionC: "Pseudo code",
    optionD: "Modules",
    correctAnswer: "A",
    explanation: "Subroutines are basic building blocks of computer programs. In programming languages, subroutines are known as Functions.",
    explanationTamil: "துணை நிரல்கள் (Subroutines) என்பது கணினி நிரல்களின் அடிப்படை கட்டுமானத் தொகுதிகள் ஆகும்.",
  },
  {
    chapterId: "cs-ch-1",
    subjectId: "sub-cs",
    stream: "Computer Science",
    sourceType: "Book-In",
    status: "Teacher Review",
    difficulty: "Easy",
    sourceTextbookId: CS_BOOK_ID,
    sourcePage: 14,
    sourceQuestionNumber: 2,
    sourcePresentation: "Text",
    questionText: "Which of the following is a unit of code that is often defined within a greater code structure?",
    questionTextTamil: "கீழ்க்கண்டவற்றுள் எது பெரும்பாலும் ஒரு பெரிய நிரல் கட்டமைப்பிற்குள் வரையறுக்கப்படும் குறிமுறையின் அலகு?",
    optionA: "Subroutines",
    optionB: "Function",
    optionC: "Files",
    optionD: "Modules",
    correctAnswer: "B",
    explanation: "A function is a unit of code that is often defined within a greater code structure, working on inputs to produce an output.",
    explanationTamil: "செயற்கூறு (Function) என்பது ஒரு பெரிய குறிமுறைக் கட்டமைப்பில் வரையறுக்கப்படும் ஒரு குறிமுறை அலகு ஆகும்.",
  },
  {
    chapterId: "cs-ch-1",
    subjectId: "sub-cs",
    stream: "Computer Science",
    sourceType: "Book-In",
    status: "Teacher Review",
    difficulty: "Medium",
    sourceTextbookId: CS_BOOK_ID,
    sourcePage: 14,
    sourceQuestionNumber: 3,
    sourcePresentation: "Text",
    questionText: "Which of the following is a distinct syntactic block?",
    questionTextTamil: "கீழ்க்கண்டவற்றுள் எது ஒரு தனித்துவமான தொடரியல் தொகுதி ஆகும்?",
    optionA: "Subroutines",
    optionB: "Function",
    optionC: "Definition",
    optionD: "Modules",
    correctAnswer: "C",
    explanation: "Definitions are distinct syntactic blocks that bind a value or function logic to a name.",
    explanationTamil: "வரையறைகள் (Definitions) என்பது தனித்துவமான தொடரியல் தொகுதிகள் ஆகும்.",
  },
  {
    chapterId: "cs-ch-1",
    subjectId: "sub-cs",
    stream: "Computer Science",
    sourceType: "Book-In",
    status: "Teacher Review",
    difficulty: "Easy",
    sourceTextbookId: CS_BOOK_ID,
    sourcePage: 14,
    sourceQuestionNumber: 4,
    sourcePresentation: "Text",
    questionText: "The variables in a function definition are called as:",
    questionTextTamil: "செயற்கூறு வரையறையில் உள்ள மாறிகள் எவ்வாறு அழைக்கப்படுகின்றன?",
    optionA: "Subroutines",
    optionB: "Function",
    optionC: "Definition",
    optionD: "Parameters",
    correctAnswer: "D",
    explanation: "Parameters are variables in a function definition that receive values when the function is called.",
    explanationTamil: "செயற்கூறு வரையறையில் உள்ள மாறிகள் அளபுருக்கள் (Parameters) எனப்படும்.",
  },
  {
    chapterId: "cs-ch-1",
    subjectId: "sub-cs",
    stream: "Computer Science",
    sourceType: "Book-In",
    status: "Teacher Review",
    difficulty: "Easy",
    sourceTextbookId: CS_BOOK_ID,
    sourcePage: 14,
    sourceQuestionNumber: 5,
    sourcePresentation: "Text",
    questionText: "The values which are passed to a function definition are called:",
    questionTextTamil: "செயற்கூறு வரையறைக்கு அனுப்பப்படும் மதிப்புகள் எவ்வாறு அழைக்கப்படுகின்றன?",
    optionA: "Arguments",
    optionB: "Subroutines",
    optionC: "Function",
    optionD: "Definition",
    correctAnswer: "A",
    explanation: "Arguments are the actual values passed to a function call and bound to the parameters.",
    explanationTamil: "செயற்கூறு அழைப்பிற்கு அனுப்பப்படும் உண்மையான மதிப்புகள் செயலுருபுகள் (Arguments) எனப்படும்.",
  },
  {
    chapterId: "cs-ch-1",
    subjectId: "sub-cs",
    stream: "Computer Science",
    sourceType: "Book-In",
    status: "Teacher Review",
    difficulty: "Medium",
    sourceTextbookId: CS_BOOK_ID,
    sourcePage: 14,
    sourceQuestionNumber: 6,
    sourcePresentation: "Text",
    questionText: "Which of the following are mandatory to write the type annotations in the function definition?",
    questionTextTamil: "செயற்கூறு வரையறையில் தரவு வகை குறிப்புகளை எழுத எது கட்டாயமானது?",
    optionA: "Curly braces",
    optionB: "Parentheses",
    optionC: "Square brackets",
    optionD: "indentations",
    correctAnswer: "B",
    explanation: "When specifying parameter and return types explicitly in typed functional definitions, parentheses around the typed expression are mandatory.",
    explanationTamil: "வகை குறிப்புகளை எழுதும் போது அடைப்புக்குறிகள் (Parentheses) கட்டாயமாகும்.",
  },
  {
    chapterId: "cs-ch-1",
    subjectId: "sub-cs",
    stream: "Computer Science",
    sourceType: "Book-In",
    status: "Teacher Review",
    difficulty: "Medium",
    sourceTextbookId: CS_BOOK_ID,
    sourcePage: 14,
    sourceQuestionNumber: 7,
    sourcePresentation: "Text",
    questionText: "Which of the following defines what an object can do?",
    questionTextTamil: "ஒரு பொருள் என்ன செய்ய முடியும் என்பதை வரையறுப்பது எது?",
    optionA: "Operating System",
    optionB: "Compiler",
    optionC: "Interface",
    optionD: "Interpreter",
    correctAnswer: "C",
    explanation: "An interface defines what an object can do (the visible contract or set of actions) without revealing how it works.",
    explanationTamil: "இடைமுகம் (Interface) என்பது ஒரு பொருள் என்ன செய்ய முடியும் என்பதை வரையறுக்கிறது.",
  },
  {
    chapterId: "cs-ch-1",
    subjectId: "sub-cs",
    stream: "Computer Science",
    sourceType: "Book-In",
    status: "Teacher Review",
    difficulty: "Medium",
    sourceTextbookId: CS_BOOK_ID,
    sourcePage: 14,
    sourceQuestionNumber: 8,
    sourcePresentation: "Text",
    questionText: "Which of the following carries out the instructions defined in the interface?",
    questionTextTamil: "இடைமுகத்தில் வரையறுக்கப்பட்ட வழிமுறைகளை செயல்படுத்துவது எது?",
    optionA: "Operating System",
    optionB: "Compiler",
    optionC: "Implementation",
    optionD: "Interpreter",
    correctAnswer: "C",
    explanation: "Implementation carries out the instructions and internal algorithms defined in the interface contract.",
    explanationTamil: "செயல்படுத்துதல் (Implementation) என்பது இடைமுகத்தில் உள்ள வழிமுறைகளை நிறைவேற்றுகிறது.",
  },
  {
    chapterId: "cs-ch-1",
    subjectId: "sub-cs",
    stream: "Computer Science",
    sourceType: "Book-In",
    status: "Teacher Review",
    difficulty: "Easy",
    sourceTextbookId: CS_BOOK_ID,
    sourcePage: 14,
    sourceQuestionNumber: 9,
    sourcePresentation: "Text",
    questionText: "The functions which will give exact result when same arguments are passed are called:",
    questionTextTamil: "ஒரே செயலுருபுகள் அனுப்பப்படும் போது எப்போதும் ஒரே சரியான விடையை வழங்கும் செயற்கூறுகள்:",
    optionA: "Impure functions",
    optionB: "Partial Functions",
    optionC: "Dynamic Functions",
    optionD: "Pure functions",
    correctAnswer: "D",
    explanation: "Pure functions always evaluate to the exact same result given the same arguments and possess referential transparency.",
    explanationTamil: "தூய செயற்கூறுகள் (Pure functions) ஒரே உள்ளீடுகளுக்கு எப்போதும் ஒரே முடிவை வழங்கும்.",
  },
  {
    chapterId: "cs-ch-1",
    subjectId: "sub-cs",
    stream: "Computer Science",
    sourceType: "Book-In",
    status: "Teacher Review",
    difficulty: "Easy",
    sourceTextbookId: CS_BOOK_ID,
    sourcePage: 15,
    sourceQuestionNumber: 10,
    sourcePresentation: "Text",
    questionText: "The functions which cause side effects to the arguments passed are called:",
    questionTextTamil: "அனுப்பப்படும் செயலுருபுகளில் பக்கவிளைவுகளை ஏற்படுத்தும் செயற்கூறுகள்:",
    optionA: "impure function",
    optionB: "Partial Functions",
    optionC: "Dynamic Functions",
    optionD: "Pure functions",
    correctAnswer: "A",
    explanation: "Impure functions depend on or mutate external/global state, causing side effects beyond their return value.",
    explanationTamil: "பக்கவிளைவுகளை ஏற்படுத்தும் செயற்கூறுகள் தூய்மையற்ற செயற்கூறு (Impure function) எனப்படும்.",
  },

  // ================= CHAPTER 2: DATA ABSTRACTION =================
  {
    chapterId: "cs-ch-2",
    subjectId: "sub-cs",
    stream: "Computer Science",
    sourceType: "Book-In",
    status: "Teacher Review",
    difficulty: "Easy",
    sourceTextbookId: CS_BOOK_ID,
    sourcePage: 24,
    sourceQuestionNumber: 1,
    sourcePresentation: "Text",
    questionText: "Which of the following functions that build the abstract data type?",
    questionTextTamil: "அருவமாக்கப்பட்ட தரவு வகையை உருவாக்கும் செயற்கூறுகள் எவை?",
    optionA: "Constructors",
    optionB: "Destructors",
    optionC: "recursive",
    optionD: "Nested",
    correctAnswer: "A",
    explanation: "Constructors are functions that build the abstract data type by putting together pieces of information.",
    explanationTamil: "ஆக்கிகள் (Constructors) என்பது அருவமாக்கப்பட்ட தரவு வகையை உருவாக்கும் செயற்கூறுகள் ஆகும்.",
  },
  {
    chapterId: "cs-ch-2",
    subjectId: "sub-cs",
    stream: "Computer Science",
    sourceType: "Book-In",
    status: "Teacher Review",
    difficulty: "Easy",
    sourceTextbookId: CS_BOOK_ID,
    sourcePage: 24,
    sourceQuestionNumber: 2,
    sourcePresentation: "Text",
    questionText: "Which of the following functions that retrieve information from the data type?",
    questionTextTamil: "தரவு வகையிலிருந்து தகவலை மீட்டெடுக்கும் செயற்கூறுகள் எவை?",
    optionA: "Constructors",
    optionB: "Selectors",
    optionC: "recursive",
    optionD: "Nested",
    correctAnswer: "B",
    explanation: "Selectors are functions that retrieve individual parts of information from the abstract data type.",
    explanationTamil: "தெரிவிப்பிகள் (Selectors) என்பது தரவு வகையிலிருந்து தகவல்களைப் பிரித்தெடுக்கும் செயற்கூறுகள் ஆகும்.",
  },
  {
    chapterId: "cs-ch-2",
    subjectId: "sub-cs",
    stream: "Computer Science",
    sourceType: "Book-In",
    status: "Teacher Review",
    difficulty: "Easy",
    sourceTextbookId: CS_BOOK_ID,
    sourcePage: 24,
    sourceQuestionNumber: 3,
    sourcePresentation: "Text",
    questionText: "The data structure which is a mutable ordered sequence of elements is called:",
    questionTextTamil: "மாற்றக்கூடிய உறுப்புகளின் வரிசைப்படுத்தப்பட்ட தொடர் தரவு அமைப்பு எது?",
    optionA: "Built in",
    optionB: "List",
    optionC: "Tuple",
    optionD: "Derived data",
    correctAnswer: "B",
    explanation: "A List in Python is an ordered, mutable sequence of items enclosed in square brackets [].",
    explanationTamil: "பட்டியல் (List) என்பது உறுப்புகளை மாற்றக்கூடிய வரிசைப்படுத்தப்பட்ட தரவு அமைப்பு ஆகும்.",
  },
  {
    chapterId: "cs-ch-2",
    subjectId: "sub-cs",
    stream: "Computer Science",
    sourceType: "Book-In",
    status: "Teacher Review",
    difficulty: "Easy",
    sourceTextbookId: CS_BOOK_ID,
    sourcePage: 24,
    sourceQuestionNumber: 4,
    sourcePresentation: "Text",
    questionText: "A sequence of immutable objects is called:",
    questionTextTamil: "மாற்ற முடியாத பொருள்களின் வரிசை அமைப்பு:",
    optionA: "Built in",
    optionB: "List",
    optionC: "Tuple",
    optionD: "Derived data",
    correctAnswer: "C",
    explanation: "A Tuple is an immutable sequence of elements enclosed in parentheses (). Once created, its items cannot be modified.",
    explanationTamil: "டியூப்பிள் (Tuple) என்பது மாற்ற முடியாத பொருள்களின் வரிசை அமைப்பாகும்.",
  },
  {
    chapterId: "cs-ch-2",
    subjectId: "sub-cs",
    stream: "Computer Science",
    sourceType: "Book-In",
    status: "Teacher Review",
    difficulty: "Medium",
    sourceTextbookId: CS_BOOK_ID,
    sourcePage: 24,
    sourceQuestionNumber: 5,
    sourcePresentation: "Text",
    questionText: "The data type whose representation is known are called:",
    questionTextTamil: "உருவமைப்பு தெரிந்த தரவு வகை எவ்வாறு அழைக்கப்படுகிறது?",
    optionA: "Built in datatype",
    optionB: "Derived datatype",
    optionC: "Concrete datatype",
    optionD: "Abstract datatype",
    correctAnswer: "C",
    explanation: "A concrete data type is a representation whose underlying structure and implementation details are directly known to the programmer.",
    explanationTamil: "உருவமைப்பு தெரிந்த தரவு வகை பருப்பொருள் தரவு வகை (Concrete datatype) எனப்படும்.",
  },
  {
    chapterId: "cs-ch-2",
    subjectId: "sub-cs",
    stream: "Computer Science",
    sourceType: "Book-In",
    status: "Teacher Review",
    difficulty: "Medium",
    sourceTextbookId: CS_BOOK_ID,
    sourcePage: 24,
    sourceQuestionNumber: 6,
    sourcePresentation: "Text",
    questionText: "The data type whose representation is unknown are called:",
    questionTextTamil: "உருவமைப்பு தெரியாத தரவு வகை எவ்வாறு அழைக்கப்படுகிறது?",
    optionA: "Built in datatype",
    optionB: "Derived datatype",
    optionC: "Concrete datatype",
    optionD: "Abstract datatype",
    correctAnswer: "D",
    explanation: "An abstract data type (ADT) is a data type whose internal representation is hidden and unknown outside its constructors and selectors.",
    explanationTamil: "உருவமைப்பு மறைக்கப்பட்ட தரவு வகை அருவமாக்கப்பட்ட தரவு வகை (Abstract datatype) எனப்படும்.",
  },
  {
    chapterId: "cs-ch-2",
    subjectId: "sub-cs",
    stream: "Computer Science",
    sourceType: "Book-In",
    status: "Teacher Review",
    difficulty: "Easy",
    sourceTextbookId: CS_BOOK_ID,
    sourcePage: 24,
    sourceQuestionNumber: 7,
    sourcePresentation: "Text",
    questionText: "Which of the following is a compound structure?",
    questionTextTamil: "கீழ்க்கண்டவற்றுள் எது ஒரு கூட்டு கட்டமைப்பு ஆகும்?",
    optionA: "Pair",
    optionB: "Triplet",
    optionC: "single",
    optionD: "quadrat",
    correctAnswer: "A",
    explanation: "A Pair is a compound structure made up of two items (represented using lists or tuples).",
    explanationTamil: "ஜோடி (Pair) என்பது இரண்டு பகுதிகளைக் கொண்ட ஒரு கூட்டு அமைப்பாகும்.",
  },
  {
    chapterId: "cs-ch-2",
    subjectId: "sub-cs",
    stream: "Computer Science",
    sourceType: "Book-In",
    status: "Teacher Review",
    difficulty: "Easy",
    sourceTextbookId: CS_BOOK_ID,
    sourcePage: 25,
    sourceQuestionNumber: 8,
    sourcePresentation: "Text",
    questionText: "Bundling two values together into one can be considered as:",
    questionTextTamil: "இரண்டு மதிப்புகளை ஒன்றாக இணைப்பது எவ்வாறு கருதப்படுகிறது?",
    optionA: "Pair",
    optionB: "Triplet",
    optionC: "single",
    optionD: "quadrat",
    correctAnswer: "A",
    explanation: "Bundling two values together into one single entity is called a Pair.",
    explanationTamil: "இரண்டு மதிப்புகளை ஒன்றாக இணைப்பது ஜோடி (Pair) எனப்படும்.",
  },
  {
    chapterId: "cs-ch-2",
    subjectId: "sub-cs",
    stream: "Computer Science",
    sourceType: "Book-In",
    status: "Teacher Review",
    difficulty: "Medium",
    sourceTextbookId: CS_BOOK_ID,
    sourcePage: 25,
    sourceQuestionNumber: 9,
    sourcePresentation: "Text",
    questionText: "Which of the following allow to name the various parts of a multi-item object?",
    questionTextTamil: "பல உருப்படிகளைக் கொண்ட பொருளின் பல்வேறு பகுதிகளுக்கு பெயரிட அனுமதிப்பது எது?",
    optionA: "Tuples",
    optionB: "Lists",
    optionC: "Classes",
    optionD: "quadrats",
    correctAnswer: "C",
    explanation: "Classes in object-oriented programming allow naming of the various individual attributes and methods of a multi-item object.",
    explanationTamil: "இனக்குழுக்கள் (Classes) பல உருப்படி பொருள்களின் பகுதிகளுக்கு பெயரிட அனுமதிக்கின்றன.",
  },
  {
    chapterId: "cs-ch-2",
    subjectId: "sub-cs",
    stream: "Computer Science",
    sourceType: "Book-In",
    status: "Teacher Review",
    difficulty: "Easy",
    sourceTextbookId: CS_BOOK_ID,
    sourcePage: 25,
    sourceQuestionNumber: 10,
    sourcePresentation: "Text",
    questionText: "Which of the following is constructed by placing expressions within square brackets?",
    questionTextTamil: "சதுர அடைப்புக்குறிக்குள் [ ] கோவைகளை வைப்பதன் மூலம் உருவாக்கப்படுவது எது?",
    optionA: "Tuples",
    optionB: "Lists",
    optionC: "Classes",
    optionD: "quadrats",
    correctAnswer: "B",
    explanation: "A list is created in Python by placing comma-separated values inside square brackets [].",
    explanationTamil: "சதுர அடைப்புக்குறிக்குள் கோவைகளை அமைத்து பட்டியல் (Lists) உருவாக்கப்படுகிறது.",
  },
];

console.log("Chapters 1-2 defined:", csQuestionsData.length);
